### ISSUE TITLE
JSON信息并不生效

### ISSUE THREAD

**Issue by ghost** [TRCStudioDean/LiteAnnouncer#1]
我在配置文件里按照实例格式添加了json信息和变量，但是并未在游戏内显示。控制台倒是有相应的信息。
配置文件如下
[Announcements.zip](https://github.com/TRCStudioDean/LiteAnnouncer/files/6735979/Announcements.zip)

**Comment by TRCStudioDean** [comment]
等待修复

**Comment by TRCStudioDean** [comment]
已解决
