### ISSUE TITLE
Unsure how to make announcements appear on a schedule automagically

### ISSUE THREAD

**Issue by nunavailabul** [TRCStudioDean/LiteAnnouncer#9]
Am adding an issue here, as requested in the discussion thread on spigot.

Paper version 1.21.1-127-master@14a48cd (2024-10-20T23:19:03Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
LiteAnnouncer version 1.3.1.3

[LiteAnnouncer.zip](https://github.com/user-attachments/files/17878464/LiteAnnouncer.zip)

**Comment by TRCStudioDean** [comment]
![image](https://github.com/user-attachments/assets/6052b8b2-1143-4845-9185-427b1dacd48d)
You must be add announcements name to here

**Comment by nunavailabul** [comment]
I knew I was just stupid.   TY!  <3
